version: '3'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: django_boilarplate
    ports:
      - "8000:8080"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    command: daphne -b 0.0.0.0 -p 8080 core.asgi:application
