# Generated by Django 5.1.2 on 2024-12-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
