name: Docker Build and Deploy Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # need to set this secrets to the git repo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: potential/boilerplate
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          # need to set this secrets to the git repo
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /var/dev/django_boilerplate
            sudo docker compose pull 
            sudo docker compose up -d --build --force-recreate
            sudo docker system prune -f